<a href="https://colab.research.google.com/github/ADavid096/pokeproject/blob/main/Script_infoDB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Base de Datos Pokemon
Por medio del siguiente script en python se obtendra la información de las tablas necesarias para el pokeproject.
## Tablas:
- Tabla Pokemon (id_pokemon, id_global, nombre, ...)
- Tabla Especies (id_especie, id_pokemon, nombre, ...)
- Tabla Formas (id_forma, nombre_forma, id_pokemon, ...)
- Tabla Tipos (id_tipo, nombre, descripcion, imagen)(OK)
- Tabla Generacion (id_gen, numero, region)(OK)
- Tabla Juegos (id_juegos,id_gen, nombre, )
- Tabla Naturalezas (id_naturaleza, nombre, generacion_origen)
- Tabla Estados (id_estado, nombre, efecto)
- Tabla Objetos (id_objeto, nombre, descripcion, imagen, efecto, generacion)
- Tabla Habilidades (id_habilidad,id_nombre)
- Tabla Lugares (id_lugar, id_gen, desc_lugar, imagen)
- Tabla Temas Musicales (id_tema, nombre, duracion, clase)
- Tabla Reglas (id_reglas, nombre)
- Tabla ClaseDaño (idclase, nombre)

In [3]:
import requests # Para realizar la descarga de info de PokeAPI
import pandas as pd # Para transformar la data

## Tabla Pokemon

In [4]:
#Listado de los pokemon segun pokedex global
url_listado_pokemon = "https://pokeapi.co/api/v2/pokemon?limit=10000"
response = requests.get(url_listado_pokemon)
listado_pokemon = response.json()
#Visualizar listado
print(listado_pokemon.keys())
print(listado_pokemon.values())

dict_keys(['count', 'next', 'previous', 'results'])

In [5]:
#Actualmente la pokedex va desde el 1 al 1025 (1025)
#Las variantes empiezan a partir de 10000 a 10325 (325)
# 1025 + 325 = 1350
print(listado_pokemon["count"])
print(listado_pokemon["results"])
print(listado_pokemon["results"][0].keys())
print(listado_pokemon["results"][0]["url"].split("/")[-2],":",listado_pokemon["results"][0]["name"])
#Se crea el diccionario que guardara los valores basicos de los pokemon
poke_global = {"poke_id":[],"poke_name":[]}
#Se llena el diccionario con los valores del response
for i in listado_pokemon["results"]:
  poke_global["poke_id"].append(i["url"].split("/")[-2])
  poke_global["poke_name"].append(i["name"])

1351

In [6]:
#Se guarda los pokemon en dataframe
import pandas as pd
tabla_pokemon = pd.DataFrame(poke_global)
tabla_pokemon

     poke_id                poke_name
0          1                bulbasaur
1          2                  ivysaur
2          3                 venusaur
3          4               charmander
4          5               charmeleon
...      ...                      ...
1346   10322     tatsugiri-curly-mega
1347   10323    tatsugiri-droopy-mega
1348   10324  tatsugiri-stretchy-mega
1349   10325          baxcalibur-mega
1350   10326     meowstic-female-mega

[1351 rows x 2 columns]

## Tabla Especies

## Tabla Formas

## Tabla Tipos

In [7]:
#Listado de los tipos
url_tipos = "https://pokeapi.co/api/v2/type/?limit=1000"
response = requests.get(url_tipos)
listado_tipos = response.json()
#Visualizar listado
#print(listado_tipos.keys())
#print(listado_tipos.values())

#Se genera un listado de urls para descargar info de los tipos
urls_tipos = []
#Se llena el diccionario con los valores del response
for i in listado_tipos["results"]:
  #tipos["id_tipo"].append(i["url"].split("/")[-2])
  #tipos["nombre_tipo"].append(i["name"])
  urls_tipos.append(i["url"])
urls_tipos

['https://pokeapi.co/api/v2/type/1/',
 'https://pokeapi.co/api/v2/type/2/',
 'https://pokeapi.co/api/v2/type/3/',
 'https://pokeapi.co/api/v2/type/4/',
 'https://pokeapi.co/api/v2/type/5/',
 'https://pokeapi.co/api/v2/type/6/',
 'https://pokeapi.co/api/v2/type/7/',
 'https://pokeapi.co/api/v2/type/8/',
 'https://pokeapi.co/api/v2/type/9/',
 'https://pokeapi.co/api/v2/type/10/',
 'https://pokeapi.co/api/v2/type/11/',
 'https://pokeapi.co/api/v2/type/12/',
 'https://pokeapi.co/api/v2/type/13/',
 'https://pokeapi.co/api/v2/type/14/',
 'https://pokeapi.co/api/v2/type/15/',
 'https://pokeapi.co/api/v2/type/16/',
 'https://pokeapi.co/api/v2/type/17/',
 'https://pokeapi.co/api/v2/type/18/',
 'https://pokeapi.co/api/v2/type/19/',
 'https://pokeapi.co/api/v2/type/10001/',
 'https://pokeapi.co/api/v2/type/10002/']

In [8]:
#Explorando la info que sale de cada link
response = requests.get(urls_tipos[17])
data = response.json()
#data["damage_relations"]# Efectividad contra otros tipos (USAR EN TABLA DE EFECTIVIDAD TIPO TIPO POR GEN)
# 'double_damage_from', 'double_damage_to', 'half_damage_from', 'half_damage_to', 'no_damage_from', 'no_damage_to'
#data["game_indices"]#(NO USAR) Id en diferentes juegos
#data["generation"]# (USAR) Generacion en la que salio
#data["id"]# (USAR) Id
#data["move_damage_class"]# (USAR) clase de daño de movimiento(de 1era a 3era, los tipos que no son gen 1 a 3 no tienen este dato)
#data["name"]# (USAR) Nombre en ingles
#data["names"]# Nombre en distintos idiomas (NO USAR)
#data["past_damage_relations"]# Efectividad contra tipos de generaciones pasadas (MODIFICACIONES A PARTIR DE X GEN)(USAR EN TABLA DE EFECTIVIDAD TIPO TIPO POR GEN)
#data["pokemon"]# (USAR PARA FORMAPOKEMONGEN) Pokemon con este tipo y el slot en el cual lo tienen presente
#data["sprites"]# (USAR) Imagen por generacion

In [9]:
# Desde 1era a 3era Gen el tipo indica que clase de daño se realiza:
# Tipos Especiales: Fuego, Agua, Planta, Eléctrico, Psíquico, Hielo, Dragón y Siniestro.
# Tipos Físicos: Normal, Lucha, Volador, Veneno, Tierra, Roca, Bicho, Fantasma y Acero.
# Tipos que no se usan o para mecanicas: Stellar(Para Teracristalizacion), Shadow(de juegos con otra mecanica), Unknown(no se usa)

In [10]:
# Obtener un listado de las claves para los diccionarios para el dataframe
claves = list(data.keys())
claves.pop(claves.index("names"))
claves.pop(claves.index("game_indices"))
claves

['damage_relations',
 'generation',
 'id',
 'move_damage_class',
 'moves',
 'name',
 'past_damage_relations',
 'pokemon',
 'sprites']

In [11]:
# Obtener listado de diccionarios con toda la informacion de los tipos.
lista_tipe=[]
for y in range(len(urls_tipos)):
  tipe={}
  response1 = requests.get(urls_tipos[y])
  for clave in claves:
      datax = response1.json()
      tipe[clave] = datax[clave]
  lista_tipe.append(tipe)
  print(y,": ",lista_tipe[y]["name"]," ",lista_tipe[y]["pokemon"])

0 :  normal   [{'pokemon': {'name': 'pidgey', 'url': 'https://pokeapi.co/api/v2/pokemon/16/'}, 'slot': 1}, {'pokemon': {'name': 'pidgeotto', 'url': 'https://pokeapi.co/api/v2/pokemon/17/'}, 'slot': 1}, {'pokemon': {'name': 'pidgeot', 'url': 'https://pokeapi.co/api/v2/pokemon/18/'}, 'slot': 1}, {'pokemon': {'name': 'rattata', 'url': 'https://pokeapi.co/api/v2/pokemon/19/'}, 'slot': 1}, {'pokemon': {'name': 'raticate', 'url': 'https://pokeapi.co/api/v2/pokemon/20/'}, 'slot': 1}, {'pokemon': {'name': 'spearow', 'url': 'https://pokeapi.co/api/v2/pokemon/21/'}, 'slot': 1}, {'pokemon': {'name': 'fearow', 'url': 'https://pokeapi.co/api/v2/pokemon/22/'}, 'slot': 1}, {'pokemon': {'name': 'jigglypuff', 'url': 'https://pokeapi.co/api/v2/pokemon/39/'}, 'slot': 1}, {'pokemon': {'name': 'wigglytuff', 'url': 'https://pokeapi.co/api/v2/pokemon/40/'}, 'slot': 1}, {'pokemon': {'name': 'meowth', 'url': 'https://pokeapi.co/api/v2/pokemon/52/'}, 'slot': 1}, {'pokemon': {'name': 'persian', 'url': 'https://pokeapi.co/api/v2/pokemon/53/'}, 'slot': 1}, {'pokemon': {'name': 'farfetchd', 'url': 'https://pokeapi.co/api/v2/pokemon/83/'}, 'slot': 1}, {'pokemon': {'name': 'doduo', 'url': 'https://pokeapi.co/api/v2/pokemon/84/'}, 'slot': 1}, {'pokemon': {'name': 'dodrio', 'url': 'https://pokeapi.co/api/v2/pokemon/85/'}, 'slot': 1}, {'pokemon': {'name': 'lickitung', 'url': 'https://pokeapi.co/api/v2/pokemon/108/'}, 'slot': 1}, {'pokemon': {'name': 'chansey', 'url': 'https://pokeapi.co/api/v2/pokemon/113/'}, 'slot': 1}, {'pokemon': {'name': 'kangaskhan', 'url': 'https://pokeapi.co/api/v2/pokemon/115/'}, 'slot': 1}, {'pokemon': {'name': 'tauros', 'url': 'https://pokeapi.co/api/v2/pokemon/128/'}, 'slot': 1}, {'pokemon': {'name': 'ditto', 'url': 'https://pokeapi.co/api/v2/pokemon/132/'}, 'slot': 1}, {'pokemon': {'name': 'eevee', 'url': 'https://pokeapi.co/api/v2/pokemon/133/'}, 'slot': 1}, {'pokemon': {'name': 'porygon', 'url': 'https://pokeapi.co/api/v2/pokemon/137/'}, 'slot': 1}, {'pokemon': {'name': 'snorlax', 'url': 'https://pokeapi.co/api/v2/pokemon/143/'}, 'slot': 1}, {'pokemon': {'name': 'sentret', 'url': 'https://pokeapi.co/api/v2/pokemon/161/'}, 'slot': 1}, {'pokemon': {'name': 'furret', 'url': 'https://pokeapi.co/api/v2/pokemon/162/'}, 'slot': 1}, {'pokemon': {'name': 'hoothoot', 'url': 'https://pokeapi.co/api/v2/pokemon/163/'}, 'slot': 1}, {'pokemon': {'name': 'noctowl', 'url': 'https://pokeapi.co/api/v2/pokemon/164/'}, 'slot': 1}, {'pokemon': {'name': 'igglybuff', 'url': 'https://pokeapi.co/api/v2/pokemon/174/'}, 'slot': 1}, {'pokemon': {'name': 'aipom', 'url': 'https://pokeapi.co/api/v2/pokemon/190/'}, 'slot': 1}, {'pokemon': {'name': 'girafarig', 'url': 'https://pokeapi.co/api/v2/pokemon/203/'}, 'slot': 1}, {'pokemon': {'name': 'dunsparce', 'url': 'https://pokeapi.co/api/v2/pokemon/206/'}, 'slot': 1}, {'pokemon': {'name': 'teddiursa', 'url': 'https://pokeapi.co/api/v2/pokemon/216/'}, 'slot': 1}, {'pokemon': {'name': 'ursaring', 'url': 'https://pokeapi.co/api/v2/pokemon/217/'}, 'slot': 1}, {'pokemon': {'name': 'porygon2', 'url': 'https://pokeapi.co/api/v2/pokemon/233/'}, 'slot': 1}, {'pokemon': {'name': 'stantler', 'url': 'https://pokeapi.co/api/v2/pokemon/234/'}, 'slot': 1}, {'pokemon': {'name': 'smeargle', 'url': 'https://pokeapi.co/api/v2/pokemon/235/'}, 'slot': 1}, {'pokemon': {'name': 'miltank', 'url': 'https://pokeapi.co/api/v2/pokemon/241/'}, 'slot': 1}, {'pokemon': {'name': 'blissey', 'url': 'https://pokeapi.co/api/v2/pokemon/242/'}, 'slot': 1}, {'pokemon': {'name': 'zigzagoon', 'url': 'https://pokeapi.co/api/v2/pokemon/263/'}, 'slot': 1}, {'pokemon': {'name': 'linoone', 'url': 'https://pokeapi.co/api/v2/pokemon/264/'}, 'slot': 1}, {'pokemon': {'name': 'taillow', 'url': 'https://pokeapi.co/api/v2/pokemon/276/'}, 'slot': 1}, {'pokemon': {'name': 'swellow', 'url': 'https://pokeapi.co/api/v2/pokemon/277/'}, 'slot': 1}, {'pokemon': {'name': 'slakoth', 'url': 'https://pokeapi.co/api/v2/pokemon/287/'}, 'slot': 1}, {'pokemon': {'name': 'vigoroth', 'url': 'https://pokeapi.co/api/v2/pokemon/288/'}, 'slot': 1}, {'pokemon': {'name': 'slaking', 'url': 'https://pokeapi.co/api/v2/pokemon/289/'}, 'slot': 1}, {'pokemon': {'name': 'whismur', 'url': 'https://pokeapi.co/api/v2/pokemon/293/'}, 'slot': 1}, {'pokemon': {'name': 'loudred', 'url': 'https://pokeapi.co/api/v2/pokemon/294/'}, 'slot': 1}, {'pokemon': {'name': 'exploud', 'url': 'https://pokeapi.co/api/v2/pokemon/295/'}, 'slot': 1}, {'pokemon': {'name': 'azurill', 'url': 'https://pokeapi.co/api/v2/pokemon/298/'}, 'slot': 1}, {'pokemon': {'name': 'skitty', 'url': 'https://pokeapi.co/api/v2/pokemon/300/'}, 'slot': 1}, {'pokemon': {'name': 'delcatty', 'url': 'https://pokeapi.co/api/v2/pokemon/301/'}, 'slot': 1}, {'pokemon': {'name': 'spinda', 'url': 'https://pokeapi.co/api/v2/pokemon/327/'}, 'slot': 1}, {'pokemon': {'name': 'swablu', 'url': 'https://pokeapi.co/api/v2/pokemon/333/'}, 'slot': 1}, {'pokemon': {'name': 'zangoose', 'url': 'https://pokeapi.co/api/v2/pokemon/335/'}, 'slot': 1}, {'pokemon': {'name': 'castform', 'url': 'https://pokeapi.co/api/v2/pokemon/351/'}, 'slot': 1}, {'pokemon': {'name': 'kecleon', 'url': 'https://pokeapi.co/api/v2/pokemon/352/'}, 'slot': 1}, {'pokemon': {'name': 'starly', 'url': 'https://pokeapi.co/api/v2/pokemon/396/'}, 'slot': 1}, {'pokemon': {'name': 'staravia', 'url': 'https://pokeapi.co/api/v2/pokemon/397/'}, 'slot': 1}, {'pokemon': {'name': 'staraptor', 'url': 'https://pokeapi.co/api/v2/pokemon/398/'}, 'slot': 1}, {'pokemon': {'name': 'bidoof', 'url': 'https://pokeapi.co/api/v2/pokemon/399/'}, 'slot': 1}, {'pokemon': {'name': 'bibarel', 'url': 'https://pokeapi.co/api/v2/pokemon/400/'}, 'slot': 1}, {'pokemon': {'name': 'ambipom', 'url': 'https://pokeapi.co/api/v2/pokemon/424/'}, 'slot': 1}, {'pokemon': {'name': 'buneary', 'url': 'https://pokeapi.co/api/v2/pokemon/427/'}, 'slot': 1}, {'pokemon': {'name': 'lopunny', 'url': 'https://pokeapi.co/api/v2/pokemon/428/'}, 'slot': 1}, {'pokemon': {'name': 'glameow', 'url': 'https://pokeapi.co/api/v2/pokemon/431/'}, 'slot': 1}, {'pokemon': {'name': 'purugly', 'url': 'https://pokeapi.co/api/v2/pokemon/432/'}, 'slot': 1}, {'pokemon': {'name': 'happiny', 'url': 'https://pokeapi.co/api/v2/pokemon/440/'}, 'slot': 1}, {'pokemon': {'name': 'chatot', 'url': 'https://pokeapi.co/api/v2/pokemon/441/'}, 'slot': 1}, {'pokemon': {'name': 'munchlax', 'url': 'https://pokeapi.co/api/v2/pokemon/446/'}, 'slot': 1}, {'pokemon': {'name': 'lickilicky', 'url': 'https://pokeapi.co/api/v2/pokemon/463/'}, 'slot': 1}, {'pokemon': {'name': 'porygon-z', 'url': 'https://pokeapi.co/api/v2/pokemon/474/'}, 'slot': 1}, {'pokemon': {'name': 'regigigas', 'url': 'https://pokeapi.co/api/v2/pokemon/486/'}, 'slot': 1}, {'pokemon': {'name': 'arceus', 'url': 'https://pokeapi.co/api/v2/pokemon/493/'}, 'slot': 1}, {'pokemon': {'name': 'patrat', 'url': 'https://pokeapi.co/api/v2/pokemon/504/'}, 'slot': 1}, {'pokemon': {'name': 'watchog', 'url': 'https://pokeapi.co/api/v2/pokemon/505/'}, 'slot': 1}, {'pokemon': {'name': 'lillipup', 'url': 'https://pokeapi.co/api/v2/pokemon/506/'}, 'slot': 1}, {'pokemon': {'name': 'herdier', 'url': 'https://pokeapi.co/api/v2/pokemon/507/'}, 'slot': 1}, {'pokemon': {'name': 'stoutland', 'url': 'https://pokeapi.co/api/v2/pokemon/508/'}, 'slot': 1}, {'pokemon': {'name': 'pidove', 'url': 'https://pokeapi.co/api/v2/pokemon/519/'}, 'slot': 1}, {'pokemon': {'name': 'tranquill', 'url': 'https://pokeapi.co/api/v2/pokemon/520/'}, 'slot': 1}, {'pokemon': {'name': 'unfezant', 'url': 'https://pokeapi.co/api/v2/pokemon/521/'}, 'slot': 1}, {'pokemon': {'name': 'audino', 'url': 'https://pokeapi.co/api/v2/pokemon/531/'}, 'slot': 1}, {'pokemon': {'name': 'minccino', 'url': 'https://pokeapi.co/api/v2/pokemon/572/'}, 'slot': 1}, {'pokemon': {'name': 'cinccino', 'url': 'https://pokeapi.co/api/v2/pokemon/573/'}, 'slot': 1}, {'pokemon': {'name': 'deerling', 'url': 'https://pokeapi.co/api/v2/pokemon/585/'}, 'slot': 1}, {'pokemon': {'name': 'sawsbuck', 'url': 'https://pokeapi.co/api/v2/pokemon/586/'}, 'slot': 1}, {'pokemon': {'name': 'bouffalant', 'url': 'https://pokeapi.co/api/v2/pokemon/626/'}, 'slot': 1}, {'pokemon': {'name': 'rufflet', 'url': 'https://pokeapi.co/api/v2/pokemon/627/'}, 'slot': 1}, {'pokemon': {'name': 'braviary', 'url': 'https://pokeapi.co/api/v2/pokemon/628/'}, 'slot': 1}, {'pokemon': {'name': 'meloetta-aria', 'url': 'https://pokeapi.co/api/v2/pokemon/648/'}, 'slot': 1}, {'pokemon': {'name': 'bunnelby', 'url': 'https://pokeapi.co/api/v2/pokemon/659/'}, 'slot': 1}, {'pokemon': {'name': 'diggersby', 'url': 'https://pokeapi.co/api/v2/pokemon/660/'}, 'slot': 1}, {'pokemon': {'name': 'fletchling', 'url': 'https://pokeapi.co/api/v2/pokemon/661/'}, 'slot': 1}, {'pokemon': {'name': 'litleo', 'url': 'https://pokeapi.co/api/v2/pokemon/667/'}, 'slot': 2}, {'pokemon': {'name': 'pyroar-male', 'url': 'https://pokeapi.co/api/v2/pokemon/668/'}, 'slot': 2}, {'pokemon': {'name': 'furfrou', 'url': 'https://pokeapi.co/api/v2/pokemon/676/'}, 'slot': 1}, {'pokemon': {'name': 'helioptile', 'url': 'https://pokeapi.co/api/v2/pokemon/694/'}, 'slot': 2}, {'pokemon': {'name': 'heliolisk', 'url': 'https://pokeapi.co/api/v2/pokemon/695/'}, 'slot': 2}, {'pokemon': {'name': 'pikipek', 'url': 'https://pokeapi.co/api/v2/pokemon/731/'}, 'slot': 1}, {'pokemon': {'name': 'trumbeak', 'url': 'https://pokeapi.co/api/v2/pokemon/732/'}, 'slot': 1}, {'pokemon': {'name': 'toucannon', 'url': 'https://pokeapi.co/api/v2/pokemon/733/'}, 'slot': 1}, {'pokemon': {'name': 'yungoos', 'url': 'https://pokeapi.co/api/v2/pokemon/734/'}, 'slot': 1}, {'pokemon': {'name': 'gumshoos', 'url': 'https://pokeapi.co/api/v2/pokemon/735/'}, 'slot': 1}, {'pokemon': {'name': 'stufful', 'url': 'https://pokeapi.co/api/v2/pokemon/759/'}, 'slot': 1}, {'pokemon': {'name': 'bewear', 'url': 'https://pokeapi.co/api/v2/pokemon/760/'}, 'slot': 1}, {'pokemon': {'name': 'oranguru', 'url': 'https://pokeapi.co/api/v2/pokemon/765/'}, 'slot': 1}, {'pokemon': {'name': 'type-null', 'url': 'https://pokeapi.co/api/v2/pokemon/772/'}, 'slot': 1}, {'pokemon': {'name': 'silvally', 'url': 'https://pokeapi.co/api/v2/pokemon/773/'}, 'slot': 1}, {'pokemon': {'name': 'komala', 'url': 'https://pokeapi.co/api/v2/pokemon/775/'}, 'slot': 1}, {'pokemon': {'name': 'drampa', 'url': 'https://pokeapi.co/api/v2/pokemon/780/'}, 'slot': 1}, {'pokemon': {'name': 'skwovet', 'url': 'https://pokeapi.co/api/v2/pokemon/819/'}, 'slot': 1}, {'pokemon': {'name': 'greedent', 'url': 'https://pokeapi.co/api/v2/pokemon/820/'}, 'slot': 1}, {'pokemon': {'name': 'wooloo', 'url': 'https://pokeapi.co/api/v2/pokemon/831/'}, 'slot': 1}, {'pokemon': {'name': 'dubwool', 'url': 'https://pokeapi.co/api/v2/pokemon/832/'}, 'slot': 1}, {'pokemon': {'name': 'obstagoon', 'url': 'https://pokeapi.co/api/v2/pokemon/862/'}, 'slot': 2}, {'pokemon': {'name': 'indeedee-male', 'url': 'https://pokeapi.co/api/v2/pokemon/876/'}, 'slot': 2}, {'pokemon': {'name': 'wyrdeer', 'url': 'https://pokeapi.co/api/v2/pokemon/899/'}, 'slot': 1}, {'pokemon': {'name': 'ursaluna', 'url': 'https://pokeapi.co/api/v2/pokemon/901/'}, 'slot': 2}, {'pokemon': {'name': 'lechonk', 'url': 'https://pokeapi.co/api/v2/pokemon/915/'}, 'slot': 1}, {'pokemon': {'name': 'oinkologne-male', 'url': 'https://pokeapi.co/api/v2/pokemon/916/'}, 'slot': 1}, {'pokemon': {'name': 'tandemaus', 'url': 'https://pokeapi.co/api/v2/pokemon/924/'}, 'slot': 1}, {'pokemon': {'name': 'maushold-family-of-four', 'url': 'https://pokeapi.co/api/v2/pokemon/925/'}, 'slot': 1}, {'pokemon': {'name': 'smoliv', 'url': 'https://pokeapi.co/api/v2/pokemon/928/'}, 'slot': 2}, {'pokemon': {'name': 'dolliv', 'url': 'https://pokeapi.co/api/v2/pokemon/929/'}, 'slot': 2}, {'pokemon': {'name': 'arboliva', 'url': 'https://pokeapi.co/api/v2/pokemon/930/'}, 'slot': 2}, {'pokemon': {'name': 'squawkabilly-green-plumage', 'url': 'https://pokeapi.co/api/v2/pokemon/931/'}, 'slot': 1}, {'pokemon': {'name': 'shroodle', 'url': 'https://pokeapi.co/api/v2/pokemon/944/'}, 'slot': 2}, {'pokemon': {'name': 'grafaiai', 'url': 'https://pokeapi.co/api/v2/pokemon/945/'}, 'slot': 2}, {'pokemon': {'name': 'cyclizar', 'url': 'https://pokeapi.co/api/v2/pokemon/967/'}, 'slot': 2}, {'pokemon': {'name': 'farigiraf', 'url': 'https://pokeapi.co/api/v2/pokemon/981/'}, 'slot': 1}, {'pokemon': {'name': 'dudunsparce-two-segment', 'url': 'https://pokeapi.co/api/v2/pokemon/982/'}, 'slot': 1}, {'pokemon': {'name': 'terapagos', 'url': 'https://pokeapi.co/api/v2/pokemon/1024/'}, 'slot': 1}, {'pokemon': {'name': 'meloetta-pirouette', 'url': 'https://pokeapi.co/api/v2/pokemon/10018/'}, 'slot': 1}, {'pokemon': {'name': 'kangaskhan-mega', 'url': 'https://pokeapi.co/api/v2/pokemon/10039/'}, 'slot': 1}, {'pokemon': {'name': 'audino-mega', 'url': 'https://pokeapi.co/api/v2/pokemon/10069/'}, 'slot': 1}, {'pokemon': {'name': 'pidgeot-mega', 'url': 'https://pokeapi.co/api/v2/pokemon/10073/'}, 'slot': 1}, {'pokemon': {'name': 'lopunny-mega', 'url': 'https://pokeapi.co/api/v2/pokemon/10088/'}, 'slot': 1}, {'pokemon': {'name': 'rattata-alola', 'url': 'https://pokeapi.co/api/v2/pokemon/10091/'}, 'slot': 2}, {'pokemon': {'name': 'raticate-alola', 'url': 'https://pokeapi.co/api/v2/pokemon/10092/'}, 'slot': 2}, {'pokemon': {'name': 'raticate-totem-alola', 'url': 'https://pokeapi.co/api/v2/pokemon/10093/'}, 'slot': 2}, {'pokemon': {'name': 'gumshoos-totem', 'url': 'https://pokeapi.co/api/v2/pokemon/10121/'}, 'slot': 1}, {'pokemon': {'name': 'eevee-starter', 'url': 'https://pokeapi.co/api/v2/pokemon/10159/'}, 'slot': 1}, {'pokemon': {'name': 'zigzagoon-galar', 'url': 'https://pokeapi.co/api/v2/pokemon/10174/'}, 'slot': 2}, {'pokemon': {'name': 'linoone-galar', 'url': 'https://pokeapi.co/api/v2/pokemon/10175/'}, 'slot': 2}, {'pokemon': {'name': 'indeedee-female', 'url': 'https://pokeapi.co/api/v2/pokemon/10186/'}, 'slot': 2}, {'pokemon': {'name': 'meowth-gmax', 'url': 'https://pokeapi.co/api/v2/pokemon/10200/'}, 'slot': 1}, {'pokemon': {'name': 'eevee-gmax', 'url': 'https://pokeapi.co/api/v2/pokemon/10205/'}, 'slot': 1}, {'pokemon': {'name': 'snorlax-gmax', 'url': 'https://pokeapi.co/api/v2/pokemon/10206/'}, 'slot': 1}, {'pokemon': {'name': 'zorua-hisui', 'url': 'https://pokeapi.co/api/v2/pokemon/10238/'}, 'slot': 1}, {'pokemon': {'name': 'zoroark-hisui', 'url': 'https://pokeapi.co/api/v2/pokemon/10239/'}, 'slot': 1}, {'pokemon': {'name': 'oinkologne-female', 'url': 'https://pokeapi.co/api/v2/pokemon/10254/'}, 'slot': 1}, {'pokemon': {'name': 'dudunsparce-three-segment', 'url': 'https://pokeapi.co/api/v2/pokemon/10255/'}, 'slot': 1}, {'pokemon': {'name': 'maushold-family-of-three', 'url': 'https://pokeapi.co/api/v2/pokemon/10257/'}, 'slot': 1}, {'pokemon': {'name': 'squawkabilly-blue-plumage', 'url': 'https://pokeapi.co/api/v2/pokemon/10260/'}, 'slot': 1}, {'pokemon': {'name': 'squawkabilly-yellow-plumage', 'url': 'https://pokeapi.co/api/v2/pokemon/10261/'}, 'slot': 1}, {'pokemon': {'name': 'squawkabilly-white-plumage', 'url': 'https://pokeapi.co/api/v2/pokemon/10262/'}, 'slot': 1}, {'pokemon': {'name': 'ursaluna-bloodmoon', 'url': 'https://pokeapi.co/api/v2/pokemon/10272/'}, 'slot': 2}, {'pokemon': {'name': 'terapagos-terastal', 'url': 'https://pokeapi.co/api/v2/pokemon/10276/'}, 'slot': 1}, {'pokemon': {'name': 'terapagos-stellar', 'url': 'https://pokeapi.co/api/v2/pokemon/10277/'}, 'slot': 1}, {'pokemon': {'name': 'pyroar-mega', 'url': 'https://pokeapi.co/api/v2/pokemon/10295/'}, 'slot': 2}, {'pokemon': {'name': 'drampa-mega', 'url': 'https://pokeapi.co/api/v2/pokemon/10302/'}, 'slot': 1}]

In [12]:
# Tabla final de tipos y Conversion a Dataframe
registrostipos = pd.DataFrame(lista_tipe)
tabla_tipo = registrostipos[["id","name"]].copy()
tabla_tipo["move_damage_class"] = registrostipos["move_damage_class"].str["name"]
tabla_tipo["generation_salida"] = registrostipos["generation"].str["name"]
tabla_tipo

       id      name move_damage_class generation_salida
0       1    normal          physical      generation-i
1       2  fighting          physical      generation-i
2       3    flying          physical      generation-i
3       4    poison          physical      generation-i
4       5    ground          physical      generation-i
5       6      rock          physical      generation-i
6       7       bug          physical      generation-i
7       8     ghost          physical      generation-i
8       9     steel          physical     generation-ii
9      10      fire           special      generation-i
10     11     water           special      generation-i
11     12     grass           special      generation-i
12     13  electric           special      generation-i
13     14   psychic           special      generation-i
14     15       ice           special      generation-i
15     16    dragon           special      generation-i
16     17      dark           special     generation-ii
17     18     fairy              None     generation-vi
18     19   stellar              None     generation-ix
19  10001   unknown              None     generation-ii
20  10002    shadow              None    generation-iii

In [13]:
# Descargar el dataframe de tipos a CSV
tabla_tipo.to_csv("tablatipos.csv",index=False)

## Tabla Generacion

In [14]:
#Listado de los generacion
url_gen = "https://pokeapi.co/api/v2/generation"
response = requests.get(url_gen)
listado_gen = response.json()
x = [] # Array de urls

#Se crea el dataframe para guardar la informacion final
tabla_gen = pd.DataFrame(columns=["num_gen", "gen", "main_region"])

#Se llena el diccionario con los valores del response
for i in listado_gen["results"]:
  x.append(i["url"])
#Se llena el dataframe con las generaciones
for j in range(1,len(x)+1):
  response1 = requests.get(x[j-1])
  data1 = response1.json()
  tabla_gen.loc[len(tabla_gen)] = [j,data1["name"],data1["main_region"]["name"]]

tabla_gen

   num_gen              gen main_region
0        1     generation-i       kanto
1        2    generation-ii       johto
2        3   generation-iii       hoenn
3        4    generation-iv      sinnoh
4        5     generation-v       unova
5        6    generation-vi       kalos
6        7   generation-vii       alola
7        8  generation-viii       galar
8        9    generation-ix      paldea

In [15]:
mapa = tabla_gen.set_index("gen")["num_gen"]#Se guarda este diccionario para indicar el "num_gen" en base a la "gen"

## Tabla Generacion-Tipo

In [16]:
tipos_general=[]
tipo_json={}
for i in range(1,listado_gen["count"]+1):
  nuevos=[]#Array de diccionarios con los repetidos de la generacion anterior, con el num_gen cambiado
  response1 = requests.get(x[i-1])
  data1 = response1.json()
  print("-----------")
  print(i)#num_gen
  #Se realiza para copiar y agregar los valores repetidos de generaciones antiguas que no son nuevos(La primera vez no aplica)

  if i>1:
    anteriores = [y for y in tipos_general if y["num_gen"] == i - 1]
    print(anteriores)
    for item in anteriores:
        nuevo = item.copy()
        nuevo["num_gen"] = i
        nuevos.append(nuevo)
    tipos_general.extend(nuevos)#Se agrega los datos repetidos de la generacion i
  #Se agrega los tipos que se agregaron en la generacion i
  if(len(data1["types"])>0):
    for j in range(len(data1["types"])):
      tipo_json["num_gen"]=i
      tipo_json["id"]=data1["types"][j]["url"].split("/")[-2]
      tipo_json["name"]=data1["types"][j]["name"]
      tipos_general.append(tipo_json)
      tipo_json={}
#Visualizar el array final
print(tipos_general)

-----------
1
-----------
2
[{'num_gen': 1, 'id': '1', 'name': 'normal'}, {'num_gen': 1, 'id': '2', 'name': 'fighting'}, {'num_gen': 1, 'id': '3', 'name': 'flying'}, {'num_gen': 1, 'id': '4', 'name': 'poison'}, {'num_gen': 1, 'id': '5', 'name': 'ground'}, {'num_gen': 1, 'id': '6', 'name': 'rock'}, {'num_gen': 1, 'id': '7', 'name': 'bug'}, {'num_gen': 1, 'id': '8', 'name': 'ghost'}, {'num_gen': 1, 'id': '10', 'name': 'fire'}, {'num_gen': 1, 'id': '11', 'name': 'water'}, {'num_gen': 1, 'id': '12', 'name': 'grass'}, {'num_gen': 1, 'id': '13', 'name': 'electric'}, {'num_gen': 1, 'id': '14', 'name': 'psychic'}, {'num_gen': 1, 'id': '15', 'name': 'ice'}, {'num_gen': 1, 'id': '16', 'name': 'dragon'}]
-----------
3
[{'num_gen': 2, 'id': '1', 'name': 'normal'}, {'num_gen': 2, 'id': '2', 'name': 'fighting'}, {'num_gen': 2, 'id': '3', 'name': 'flying'}, {'num_gen': 2, 'id': '4', 'name': 'poison'}, {'num_gen': 2, 'id': '5', 'name': 'ground'}, {'num_gen': 2, 'id': '6', 'name': 'rock'}, {'num_gen': 2, 'id': '7', 'name': 'bug'}, {'num_gen': 2, 'id': '8', 'name': 'ghost'}, {'num_gen': 2, 'id': '10', 'name': 'fire'}, {'num_gen': 2, 'id': '11', 'name': 'water'}, {'num_gen': 2, 'id': '12', 'name': 'grass'}, {'num_gen': 2, 'id': '13', 'name': 'electric'}, {'num_gen': 2, 'id': '14', 'name': 'psychic'}, {'num_gen': 2, 'id': '15', 'name': 'ice'}, {'num_gen': 2, 'id': '16', 'name': 'dragon'}, {'num_gen': 2, 'id': '9', 'name': 'steel'}, {'num_gen': 2, 'id': '17', 'name': 'dark'}, {'num_gen': 2, 'id': '10001', 'name': 'unknown'}]
-----------
4
[{'num_gen': 3, 'id': '1', 'name': 'normal'}, {'num_gen': 3, 'id': '2', 'name': 'fighting'}, {'num_gen': 3, 'id': '3', 'name': 'flying'}, {'num_gen': 3, 'id': '4', 'name': 'poison'}, {'num_gen': 3, 'id': '5', 'name': 'ground'}, {'num_gen': 3, 'id': '6', 'name': 'rock'}, {'num_gen': 3, 'id': '7', 'name': 'bug'}, {'num_gen': 3, 'id': '8', 'name': 'ghost'}, {'num_gen': 3, 'id': '10', 'name': 'fire'}, {'num_gen': 3, 'id': '11', 'name': 'water'}, {'num_gen': 3, 'id': '12', 'name': 'grass'}, {'num_gen': 3, 'id': '13', 'name': 'electric'}, {'num_gen': 3, 'id': '14', 'name': 'psychic'}, {'num_gen': 3, 'id': '15', 'name': 'ice'}, {'num_gen': 3, 'id': '16', 'name': 'dragon'}, {'num_gen': 3, 'id': '9', 'name': 'steel'}, {'num_gen': 3, 'id': '17', 'name': 'dark'}, {'num_gen': 3, 'id': '10001', 'name': 'unknown'}, {'num_gen': 3, 'id': '10002', 'name': 'shadow'}]
-----------
5
[{'num_gen': 4, 'id': '1', 'name': 'normal'}, {'num_gen': 4, 'id': '2', 'name': 'fighting'}, {'num_gen': 4, 'id': '3', 'name': 'flying'}, {'num_gen': 4, 'id': '4', 'name': 'poison'}, {'num_gen': 4, 'id': '5', 'name': 'ground'}, {'num_gen': 4, 'id': '6', 'name': 'rock'}, {'num_gen': 4, 'id': '7', 'name': 'bug'}, {'num_gen': 4, 'id': '8', 'name': 'ghost'}, {'num_gen': 4, 'id': '10', 'name': 'fire'}, {'num_gen': 4, 'id': '11', 'name': 'water'}, {'num_gen': 4, 'id': '12', 'name': 'grass'}, {'num_gen': 4, 'id': '13', 'name': 'electric'}, {'num_gen': 4, 'id': '14', 'name': 'psychic'}, {'num_gen': 4, 'id': '15', 'name': 'ice'}, {'num_gen': 4, 'id': '16', 'name': 'dragon'}, {'num_gen': 4, 'id': '9', 'name': 'steel'}, {'num_gen': 4, 'id': '17', 'name': 'dark'}, {'num_gen': 4, 'id': '10001', 'name': 'unknown'}, {'num_gen': 4, 'id': '10002', 'name': 'shadow'}]
-----------
6
[{'num_gen': 5, 'id': '1', 'name': 'normal'}, {'num_gen': 5, 'id': '2', 'name': 'fighting'}, {'num_gen': 5, 'id': '3', 'name': 'flying'}, {'num_gen': 5, 'id': '4', 'name': 'poison'}, {'num_gen': 5, 'id': '5', 'name': 'ground'}, {'num_gen': 5, 'id': '6', 'name': 'rock'}, {'num_gen': 5, 'id': '7', 'name': 'bug'}, {'num_gen': 5, 'id': '8', 'name': 'ghost'}, {'num_gen': 5, 'id': '10', 'name': 'fire'}, {'num_gen': 5, 'id': '11', 'name': 'water'}, {'num_gen': 5, 'id': '12', 'name': 'grass'}, {'num_gen': 5, 'id': '13', 'name': 'electric'}, {'num_gen': 5, 'id': '14', 'name': 'psychic'}, {'num_gen': 5, 'id': '15', 'name': 'ice'}, {'num_gen': 5, 'id': '16', 'name': 'dragon'}, {'num_gen': 5, 'id': '9', 'name': 'steel'}, {'num_gen': 5, 'id': '17', 'name': 'dark'}, {'num_gen': 5, 'id': '10001', 'name': 'unknown'}, {'num_gen': 5, 'id': '10002', 'name': 'shadow'}]
-----------
7
[{'num_gen': 6, 'id': '1', 'name': 'normal'}, {'num_gen': 6, 'id': '2', 'name': 'fighting'}, {'num_gen': 6, 'id': '3', 'name': 'flying'}, {'num_gen': 6, 'id': '4', 'name': 'poison'}, {'num_gen': 6, 'id': '5', 'name': 'ground'}, {'num_gen': 6, 'id': '6', 'name': 'rock'}, {'num_gen': 6, 'id': '7', 'name': 'bug'}, {'num_gen': 6, 'id': '8', 'name': 'ghost'}, {'num_gen': 6, 'id': '10', 'name': 'fire'}, {'num_gen': 6, 'id': '11', 'name': 'water'}, {'num_gen': 6, 'id': '12', 'name': 'grass'}, {'num_gen': 6, 'id': '13', 'name': 'electric'}, {'num_gen': 6, 'id': '14', 'name': 'psychic'}, {'num_gen': 6, 'id': '15', 'name': 'ice'}, {'num_gen': 6, 'id': '16', 'name': 'dragon'}, {'num_gen': 6, 'id': '9', 'name': 'steel'}, {'num_gen': 6, 'id': '17', 'name': 'dark'}, {'num_gen': 6, 'id': '10001', 'name': 'unknown'}, {'num_gen': 6, 'id': '10002', 'name': 'shadow'}, {'num_gen': 6, 'id': '18', 'name': 'fairy'}]
-----------
8
[{'num_gen': 7, 'id': '1', 'name': 'normal'}, {'num_gen': 7, 'id': '2', 'name': 'fighting'}, {'num_gen': 7, 'id': '3', 'name': 'flying'}, {'num_gen': 7, 'id': '4', 'name': 'poison'}, {'num_gen': 7, 'id': '5', 'name': 'ground'}, {'num_gen': 7, 'id': '6', 'name': 'rock'}, {'num_gen': 7, 'id': '7', 'name': 'bug'}, {'num_gen': 7, 'id': '8', 'name': 'ghost'}, {'num_gen': 7, 'id': '10', 'name': 'fire'}, {'num_gen': 7, 'id': '11', 'name': 'water'}, {'num_gen': 7, 'id': '12', 'name': 'grass'}, {'num_gen': 7, 'id': '13', 'name': 'electric'}, {'num_gen': 7, 'id': '14', 'name': 'psychic'}, {'num_gen': 7, 'id': '15', 'name': 'ice'}, {'num_gen': 7, 'id': '16', 'name': 'dragon'}, {'num_gen': 7, 'id': '9', 'name': 'steel'}, {'num_gen': 7, 'id': '17', 'name': 'dark'}, {'num_gen': 7, 'id': '10001', 'name': 'unknown'}, {'num_gen': 7, 'id': '10002', 'name': 'shadow'}, {'num_gen': 7, 'id': '18', 'name': 'fairy'}]
-----------
9
[{'num_gen': 8, 'id': '1', 'name': 'normal'}, {'num_gen': 8, 'id': '2', 'name': 'fighting'}, {'num_gen': 8, 'id': '3', 'name': 'flying'}, {'num_gen': 8, 'id': '4', 'name': 'poison'}, {'num_gen': 8, 'id': '5', 'name': 'ground'}, {'num_gen': 8, 'id': '6', 'name': 'rock'}, {'num_gen': 8, 'id': '7', 'name': 'bug'}, {'num_gen': 8, 'id': '8', 'name': 'ghost'}, {'num_gen': 8, 'id': '10', 'name': 'fire'}, {'num_gen': 8, 'id': '11', 'name': 'water'}, {'num_gen': 8, 'id': '12', 'name': 'grass'}, {'num_gen': 8, 'id': '13', 'name': 'electric'}, {'num_gen': 8, 'id': '14', 'name': 'psychic'}, {'num_gen': 8, 'id': '15', 'name': 'ice'}, {'num_gen': 8, 'id': '16', 'name': 'dragon'}, {'num_gen': 8, 'id': '9', 'name': 'steel'}, {'num_gen': 8, 'id': '17', 'name': 'dark'}, {'num_gen': 8, 'id': '10001', 'name': 'unknown'}, {'num_gen': 8, 'id': '10002', 'name': 'shadow'}, {'num_gen': 8, 'id': '18', 'name': 'fairy'}]
[{'num_gen': 1, 'id': '1', 'name': 'normal'}, {'num_gen': 1, 'id': '2', 'name': 'fighting'}, {'num_gen': 1, 'id': '3', 'name': 'flying'}, {'num_gen': 1, 'id': '4', 'name': 'poison'}, {'num_gen': 1, 'id': '5', 'name': 'ground'}, {'num_gen': 1, 'id': '6', 'name': 'rock'}, {'num_gen': 1, 'id': '7', 'name': 'bug'}, {'num_gen': 1, 'id': '8', 'name': 'ghost'}, {'num_gen': 1, 'id': '10', 'name': 'fire'}, {'num_gen': 1, 'id': '11', 'name': 'water'}, {'num_gen': 1, 'id': '12', 'name': 'grass'}, {'num_gen': 1, 'id': '13', 'name': 'electric'}, {'num_gen': 1, 'id': '14', 'name': 'psychic'}, {'num_gen': 1, 'id': '15', 'name': 'ice'}, {'num_gen': 1, 'id': '16', 'name': 'dragon'}, {'num_gen': 2, 'id': '1', 'name': 'normal'}, {'num_gen': 2, 'id': '2', 'name': 'fighting'}, {'num_gen': 2, 'id': '3', 'name': 'flying'}, {'num_gen': 2, 'id': '4', 'name': 'poison'}, {'num_gen': 2, 'id': '5', 'name': 'ground'}, {'num_gen': 2, 'id': '6', 'name': 'rock'}, {'num_gen': 2, 'id': '7', 'name': 'bug'}, {'num_gen': 2, 'id': '8', 'name': 'ghost'}, {'num_gen': 2, 'id': '10', 'name': 'fire'}, {'num_gen': 2, 'id': '11', 'name': 'water'}, {'num_gen': 2, 'id': '12', 'name': 'grass'}, {'num_gen': 2, 'id': '13', 'name': 'electric'}, {'num_gen': 2, 'id': '14', 'name': 'psychic'}, {'num_gen': 2, 'id': '15', 'name': 'ice'}, {'num_gen': 2, 'id': '16', 'name': 'dragon'}, {'num_gen': 2, 'id': '9', 'name': 'steel'}, {'num_gen': 2, 'id': '17', 'name': 'dark'}, {'num_gen': 2, 'id': '10001', 'name': 'unknown'}, {'num_gen': 3, 'id': '1', 'name': 'normal'}, {'num_gen': 3, 'id': '2', 'name': 'fighting'}, {'num_gen': 3, 'id': '3', 'name': 'flying'}, {'num_gen': 3, 'id': '4', 'name': 'poison'}, {'num_gen': 3, 'id': '5', 'name': 'ground'}, {'num_gen': 3, 'id': '6', 'name': 'rock'}, {'num_gen': 3, 'id': '7', 'name': 'bug'}, {'num_gen': 3, 'id': '8', 'name': 'ghost'}, {'num_gen': 3, 'id': '10', 'name': 'fire'}, {'num_gen': 3, 'id': '11', 'name': 'water'}, {'num_gen': 3, 'id': '12', 'name': 'grass'}, {'num_gen': 3, 'id': '13', 'name': 'electric'}, {'num_gen': 3, 'id': '14', 'name': 'psychic'}, {'num_gen': 3, 'id': '15', 'name': 'ice'}, {'num_gen': 3, 'id': '16', 'name': 'dragon'}, {'num_gen': 3, 'id': '9', 'name': 'steel'}, {'num_gen': 3, 'id': '17', 'name': 'dark'}, {'num_gen': 3, 'id': '10001', 'name': 'unknown'}, {'num_gen': 3, 'id': '10002', 'name': 'shadow'}, {'num_gen': 4, 'id': '1', 'name': 'normal'}, {'num_gen': 4, 'id': '2', 'name': 'fighting'}, {'num_gen': 4, 'id': '3', 'name': 'flying'}, {'num_gen': 4, 'id': '4', 'name': 'poison'}, {'num_gen': 4, 'id': '5', 'name': 'ground'}, {'num_gen': 4, 'id': '6', 'name': 'rock'}, {'num_gen': 4, 'id': '7', 'name': 'bug'}, {'num_gen': 4, 'id': '8', 'name': 'ghost'}, {'num_gen': 4, 'id': '10', 'name': 'fire'}, {'num_gen': 4, 'id': '11', 'name': 'water'}, {'num_gen': 4, 'id': '12', 'name': 'grass'}, {'num_gen': 4, 'id': '13', 'name': 'electric'}, {'num_gen': 4, 'id': '14', 'name': 'psychic'}, {'num_gen': 4, 'id': '15', 'name': 'ice'}, {'num_gen': 4, 'id': '16', 'name': 'dragon'}, {'num_gen': 4, 'id': '9', 'name': 'steel'}, {'num_gen': 4, 'id': '17', 'name': 'dark'}, {'num_gen': 4, 'id': '10001', 'name': 'unknown'}, {'num_gen': 4, 'id': '10002', 'name': 'shadow'}, {'num_gen': 5, 'id': '1', 'name': 'normal'}, {'num_gen': 5, 'id': '2', 'name': 'fighting'}, {'num_gen': 5, 'id': '3', 'name': 'flying'}, {'num_gen': 5, 'id': '4', 'name': 'poison'}, {'num_gen': 5, 'id': '5', 'name': 'ground'}, {'num_gen': 5, 'id': '6', 'name': 'rock'}, {'num_gen': 5, 'id': '7', 'name': 'bug'}, {'num_gen': 5, 'id': '8', 'name': 'ghost'}, {'num_gen': 5, 'id': '10', 'name': 'fire'}, {'num_gen': 5, 'id': '11', 'name': 'water'}, {'num_gen': 5, 'id': '12', 'name': 'grass'}, {'num_gen': 5, 'id': '13', 'name': 'electric'}, {'num_gen': 5, 'id': '14', 'name': 'psychic'}, {'num_gen': 5, 'id': '15', 'name': 'ice'}, {'num_gen': 5, 'id': '16', 'name': 'dragon'}, {'num_gen': 5, 'id': '9', 'name': 'steel'}, {'num_gen': 5, 'id': '17', 'name': 'dark'}, {'num_gen': 5, 'id': '10001', 'name': 'unknown'}, {'num_gen': 5, 'id': '10002', 'name': 'shadow'}, {'num_gen': 6, 'id': '1', 'name': 'normal'}, {'num_gen': 6, 'id': '2', 'name': 'fighting'}, {'num_gen': 6, 'id': '3', 'name': 'flying'}, {'num_gen': 6, 'id': '4', 'name': 'poison'}, {'num_gen': 6, 'id': '5', 'name': 'ground'}, {'num_gen': 6, 'id': '6', 'name': 'rock'}, {'num_gen': 6, 'id': '7', 'name': 'bug'}, {'num_gen': 6, 'id': '8', 'name': 'ghost'}, {'num_gen': 6, 'id': '10', 'name': 'fire'}, {'num_gen': 6, 'id': '11', 'name': 'water'}, {'num_gen': 6, 'id': '12', 'name': 'grass'}, {'num_gen': 6, 'id': '13', 'name': 'electric'}, {'num_gen': 6, 'id': '14', 'name': 'psychic'}, {'num_gen': 6, 'id': '15', 'name': 'ice'}, {'num_gen': 6, 'id': '16', 'name': 'dragon'}, {'num_gen': 6, 'id': '9', 'name': 'steel'}, {'num_gen': 6, 'id': '17', 'name': 'dark'}, {'num_gen': 6, 'id': '10001', 'name': 'unknown'}, {'num_gen': 6, 'id': '10002', 'name': 'shadow'}, {'num_gen': 6, 'id': '18', 'name': 'fairy'}, {'num_gen': 7, 'id': '1', 'name': 'normal'}, {'num_gen': 7, 'id': '2', 'name': 'fighting'}, {'num_gen': 7, 'id': '3', 'name': 'flying'}, {'num_gen': 7, 'id': '4', 'name': 'poison'}, {'num_gen': 7, 'id': '5', 'name': 'ground'}, {'num_gen': 7, 'id': '6', 'name': 'rock'}, {'num_gen': 7, 'id': '7', 'name': 'bug'}, {'num_gen': 7, 'id': '8', 'name': 'ghost'}, {'num_gen': 7, 'id': '10', 'name': 'fire'}, {'num_gen': 7, 'id': '11', 'name': 'water'}, {'num_gen': 7, 'id': '12', 'name': 'grass'}, {'num_gen': 7, 'id': '13', 'name': 'electric'}, {'num_gen': 7, 'id': '14', 'name': 'psychic'}, {'num_gen': 7, 'id': '15', 'name': 'ice'}, {'num_gen': 7, 'id': '16', 'name': 'dragon'}, {'num_gen': 7, 'id': '9', 'name': 'steel'}, {'num_gen': 7, 'id': '17', 'name': 'dark'}, {'num_gen': 7, 'id': '10001', 'name': 'unknown'}, {'num_gen': 7, 'id': '10002', 'name': 'shadow'}, {'num_gen': 7, 'id': '18', 'name': 'fairy'}, {'num_gen': 8, 'id': '1', 'name': 'normal'}, {'num_gen': 8, 'id': '2', 'name': 'fighting'}, {'num_gen': 8, 'id': '3', 'name': 'flying'}, {'num_gen': 8, 'id': '4', 'name': 'poison'}, {'num_gen': 8, 'id': '5', 'name': 'ground'}, {'num_gen': 8, 'id': '6', 'name': 'rock'}, {'num_gen': 8, 'id': '7', 'name': 'bug'}, {'num_gen': 8, 'id': '8', 'name': 'ghost'}, {'num_gen': 8, 'id': '10', 'name': 'fire'}, {'num_gen': 8, 'id': '11', 'name': 'water'}, {'num_gen': 8, 'id': '12', 'name': 'grass'}, {'num_gen': 8, 'id': '13', 'name': 'electric'}, {'num_gen': 8, 'id': '14', 'name': 'psychic'}, {'num_gen': 8, 'id': '15', 'name': 'ice'}, {'num_gen': 8, 'id': '16', 'name': 'dragon'}, {'num_gen': 8, 'id': '9', 'name': 'steel'}, {'num_gen': 8, 'id': '17', 'name': 'dark'}, {'num_gen': 8, 'id': '10001', 'name': 'unknown'}, {'num_gen': 8, 'id': '10002', 'name': 'shadow'}, {'num_gen': 8, 'id': '18', 'name': 'fairy'}, {'num_gen': 9, 'id': '1', 'name': 'normal'}, {'num_gen': 9, 'id': '2', 'name': 'fighting'}, {'num_gen': 9, 'id': '3', 'name': 'flying'}, {'num_gen': 9, 'id': '4', 'name': 'poison'}, {'num_gen': 9, 'id': '5', 'name': 'ground'}, {'num_gen': 9, 'id': '6', 'name': 'rock'}, {'num_gen': 9, 'id': '7', 'name': 'bug'}, {'num_gen': 9, 'id': '8', 'name': 'ghost'}, {'num_gen': 9, 'id': '10', 'name': 'fire'}, {'num_gen': 9, 'id': '11', 'name': 'water'}, {'num_gen': 9, 'id': '12', 'name': 'grass'}, {'num_gen': 9, 'id': '13', 'name': 'electric'}, {'num_gen': 9, 'id': '14', 'name': 'psychic'}, {'num_gen': 9, 'id': '15', 'name': 'ice'}, {'num_gen': 9, 'id': '16', 'name': 'dragon'}, {'num_gen': 9, 'id': '9', 'name': 'steel'}, {'num_gen': 9, 'id': '17', 'name': 'dark'}, {'num_gen': 9, 'id': '10001', 'name': 'unknown'}, {'num_gen': 9, 'id': '10002', 'name': 'shadow'}, {'num_gen': 9, 'id': '18', 'name': 'fairy'}, {'num_gen': 9, 'id': '19', 'name': 'stellar'}]

In [17]:
tabla_tipos_gen = pd.DataFrame(tipos_general)
tabla_tipos_gen

     num_gen     id      name
0          1      1    normal
1          1      2  fighting
2          1      3    flying
3          1      4    poison
4          1      5    ground
..       ...    ...       ...
166        9     17      dark
167        9  10001   unknown
168        9  10002    shadow
169        9     18     fairy
170        9     19   stellar

[171 rows x 3 columns]

In [18]:
#Obtener los sprites por tipo
gencolector = []
for url in urls_tipos:
  response = requests.get(url)
  data =response.json()
  eldatas = pd.DataFrame(data["sprites"])
  sprites_url = list(eldatas.keys())#Listado de encabezados ("generation-i","generation-ii",etc)

  #Se crea el listado de diccionarios para el tipo en el listado de urls
  for c in range(len(sprites_url)):
    gensprite = {}

    eldotas = eldatas[sprites_url[c]].dropna()#Se borran todos los valores NaN
    gensprite["id"] = data["id"]
    gensprite["name"] = data["name"]
    gensprite["gen"] = sprites_url[c]#Generacion
    gensprite["spriteurl"] = eldotas.iloc[0]["name_icon"]#Imagen de la generacion
    if c==0:
      url_valor=gensprite["spriteurl"]
    gencolector.append(gensprite)

  #Agregar la primera y segunda generacion
  gencolector.append({"id":data["id"],"name":data["name"],"gen":"generation-i","spriteurl":url_valor})
  gencolector.append({"id":data["id"],"name":data["name"],"gen":"generation-ii","spriteurl":url_valor})

#Visualizar resultado
#Este dataframe bota el id tipo, el nombre del tipo y la generacion en texto y el sprite
dfgencolector =pd.DataFrame(gencolector)
#Se agrega el num_gen al final, luego de realizar el dataframe final con todos los tipos
dfgencolector["num_gen"] = dfgencolector["gen"].map(mapa)
dfgencolector

,id,name,gen,spriteurl,num_gen
0,1,normal,generation-iii,https://raw.githubusercontent.com/PokeAPI/spri...,3
1,1,normal,generation-iv,https://raw.githubusercontent.com/PokeAPI/spri...,4
2,1,normal,generation-ix,https://raw.githubusercontent.com/PokeAPI/spri...,9
3,1,normal,generation-v,https://raw.githubusercontent.com/PokeAPI/spri...,5
4,1,normal,generation-vi,https://raw.githubusercontent.com/PokeAPI/spri...,6
...,...,...,...,...,...
184,10002,shadow,generation-vi,None,6
185,10002,shadow,generation-vii,None,7
186,10002,shadow,generation-viii,None,8
187,10002,shadow,generation-i,None,1
188,10002,shadow,generation-ii,None,2

In [19]:
sprites_url

['generation-iii',
 'generation-iv',
 'generation-ix',
 'generation-v',
 'generation-vi',
 'generation-vii',
 'generation-viii']

In [20]:
#Se agrega una columna al dfgencolector y se pasa a index
dfgencolector2 = dfgencolector.copy()
dfgencolector2["num_gen-id"] = "gen-" + dfgencolector2["num_gen"].astype(str) + "-type-" + dfgencolector2["id"].astype(str)
dfgencolector2 = dfgencolector2.set_index("num_gen-id")
dfgencolector2.to_csv("pruebas.csv")

In [21]:
mapa_gen = dfgencolector2["gen"]#Serie diccionario para "gen"
mapa_spriteurl = dfgencolector2["spriteurl"]#Serie diccionario para "spriteurl"

#mapa_spriteurl.to_csv("mapa_spriteurl.csv")
#mapa_gen.to_csv("mapa_gen.csv")

In [22]:
#Se crea el nuevo dataframe con el nombre de la gen y el sprite (Tabla final Tipo-Gen)
tabla_tipos_gen2 = tabla_tipos_gen.copy()
tabla_tipos_gen2["combina"] = "gen-" + tabla_tipos_gen2["num_gen"].astype(str) + "-type-" + tabla_tipos_gen2["id"].astype(str)
tabla_tipos_gen2
#Se agrega en base a los diccionarios de "mapa_gen" y "mapa_spriteurl"
tabla_tipos_gen2["gen"] = tabla_tipos_gen2["combina"].map(mapa_gen)
tabla_tipos_gen2["spriteurl"] = tabla_tipos_gen2["combina"].map(mapa_spriteurl)
#Se elimina la columna "combina":
tabla_tipos_gen2 = tabla_tipos_gen2.drop(columns=["combina"])
#Ver resultado final
tabla_tipos_gen2.head(40)

,num_gen,id,name,gen,spriteurl
0,1,1,normal,generation-i,https://raw.githubusercontent.com/PokeAPI/spri...
1,1,2,fighting,generation-i,https://raw.githubusercontent.com/PokeAPI/spri...
2,1,3,flying,generation-i,https://raw.githubusercontent.com/PokeAPI/spri...
3,1,4,poison,generation-i,https://raw.githubusercontent.com/PokeAPI/spri...
4,1,5,ground,generation-i,https://raw.githubusercontent.com/PokeAPI/spri...
5,1,6,rock,generation-i,https://raw.githubusercontent.com/PokeAPI/spri...
6,1,7,bug,generation-i,https://raw.githubusercontent.com/PokeAPI/spri...
7,1,8,ghost,generation-i,https://raw.githubusercontent.com/PokeAPI/spri...
8,1,10,fire,generation-i,https://raw.githubusercontent.com/PokeAPI/spri...
9,1,11,water,generation-i,https://raw.githubusercontent.com/PokeAPI/spri...
10,1,12,grass,generation-i,https://raw.githubusercontent.com/PokeAPI/spri...
11,1,13,electric,generation-i,https://raw.githubusercontent.com/PokeAPI/spri...
12,1,14,psychic,generation-i,https://raw.githubusercontent.com/PokeAPI/spri...
13,1,15,ice,generation-i,https://raw.githubusercontent.com/PokeAPI/spri...
14,1,16,dragon,generation-i,https://raw.githubusercontent.com/PokeAPI/spri...
15,2,1,normal,generation-ii,https://raw.githubusercontent.com/PokeAPI/spri...
16,2,2,fighting,generation-ii,https://raw.githubusercontent.com/PokeAPI/spri...
17,2,3,flying,generation-ii,https://raw.githubusercontent.com/PokeAPI/spri...
18,2,4,poison,generation-ii,https://raw.githubusercontent.com/PokeAPI/spri...
19,2,5,ground,generation-ii,https://raw.githubusercontent.com/PokeAPI/spri...
20,2,6,rock,generation-ii,https://raw.githubusercontent.com/PokeAPI/spri...
21,2,7,bug,generation-ii,https://raw.githubusercontent.com/PokeAPI/spri...
22,2,8,ghost,generation-ii,https://raw.githubusercontent.com/PokeAPI/spri...
23,2,10,fire,generation-ii,https://raw.githubusercontent.com/PokeAPI/spri...
24,2,11,water,generation-ii,https://raw.githubusercontent.com/PokeAPI/spri...
25,2,12,grass,generation-ii,https://raw.githubusercontent.com/PokeAPI/spri...
26,2,13,electric,generation-ii,https://raw.githubusercontent.com/PokeAPI/spri...
27,2,14,psychic,generation-ii,https://raw.githubusercontent.com/PokeAPI/spri...
28,2,15,ice,generation-ii,https://raw.githubusercontent.com/PokeAPI/spri...
29,2,16,dragon,generation-ii,https://raw.githubusercontent.com/PokeAPI/spri...
30,2,9,steel,generation-ii,https://raw.githubusercontent.com/PokeAPI/spri...
31,2,17,dark,generation-ii,https://raw.githubusercontent.com/PokeAPI/spri...
32,2,10001,unknown,generation-ii,https://raw.githubusercontent.com/PokeAPI/spri...
33,3,1,normal,generation-iii,https://raw.githubusercontent.com/PokeAPI/spri...
34,3,2,fighting,generation-iii,https://raw.githubusercontent.com/PokeAPI/spri...
35,3,3,flying,generation-iii,https://raw.githubusercontent.com/PokeAPI/spri...
36,3,4,poison,generation-iii,https://raw.githubusercontent.com/PokeAPI/spri...
37,3,5,ground,generation-iii,https://raw.githubusercontent.com/PokeAPI/spri...
38,3,6,rock,generation-iii,https://raw.githubusercontent.com/PokeAPI/spri...
39,3,7,bug,generation-iii,https://raw.githubusercontent.com/PokeAPI/spri...

In [23]:
#Descargar excel final
tabla_tipos_gen2.to_csv("tabla_tipos.csv")

In [24]:
#Multiplicador por categoria
cat_multiplicador = [{"category":"double_damage_from","tipo":"from","valor":2},{"category":"double_damage_to","tipo":"to","valor":2},{"category":"half_damage_from","tipo":"from","valor":0.5},{"category":"half_damage_to","tipo":"to","valor":0.5},{"category":"no_damage_to","tipo":"to","valor":0},{"category":"no_damage_from","tipo":"from","valor":0}]

In [25]:
mapa_multiplicador = pd.DataFrame(cat_multiplicador)
mapa_multiplicador = mapa_multiplicador.set_index("category")
mapa_multiplicador

                    tipo  valor
category
double_damage_from  from    2.0
double_damage_to      to    2.0
half_damage_from    from    0.5
half_damage_to        to    0.5
no_damage_to          to    0.0
no_damage_from      from    0.0

In [26]:
#Pendiente Efectividades
lista_efectividad=[]
for url in urls_tipos:
  dic_efectividad={}
  response = requests.get(url)
  data = response.json()
  claves = list(data["damage_relations"].keys())#"past_damage_relations"
  efectividades = data["damage_relations"].values()
  contador = 0
  for i in efectividades:
    for j in i:
      dic_efectividad["id"] = data["id"]
      dic_efectividad["type1"] = data["name"]
      dic_efectividad["type2"] = j["name"]
      dic_efectividad["category"] = claves[contador]
      lista_efectividad.append(dic_efectividad)
      dic_efectividad={}
    contador = contador + 1
df_tabla_efectividad = pd.DataFrame(lista_efectividad)
df_tabla_efectividad

     id   type1     type2            category
0     1  normal  fighting  double_damage_from
1     1  normal      rock      half_damage_to
2     1  normal     steel      half_damage_to
3     1  normal     ghost      no_damage_from
4     1  normal     ghost        no_damage_to
..   ..     ...       ...                 ...
235  18   fairy      dark    half_damage_from
236  18   fairy    poison      half_damage_to
237  18   fairy     steel      half_damage_to
238  18   fairy      fire      half_damage_to
239  18   fairy    dragon      no_damage_from

[240 rows x 4 columns]

In [27]:
#Se agrega el tipo y valor y se filtra solo los tipo "to"
df_tabla_efectividad2 = df_tabla_efectividad.copy()
df_tabla_efectividad2["tipo"] = df_tabla_efectividad2["category"].map(mapa_multiplicador["tipo"])
df_tabla_efectividad2["valor"] = df_tabla_efectividad2["category"].map(mapa_multiplicador["valor"])
df_tabla_efectividad3 = df_tabla_efectividad2[df_tabla_efectividad2["tipo"]=="to"]
df_tabla_efectividad3#Tabla para utilizar de referencia para la tabla de calculos

     id     type1   type2          category tipo  valor
1     1    normal    rock    half_damage_to   to    0.5
2     1    normal   steel    half_damage_to   to    0.5
4     1    normal   ghost      no_damage_to   to    0.0
8     2  fighting  normal  double_damage_to   to    2.0
9     2  fighting    rock  double_damage_to   to    2.0
..   ..       ...     ...               ...  ...    ...
231  18     fairy  dragon  double_damage_to   to    2.0
232  18     fairy    dark  double_damage_to   to    2.0
236  18     fairy  poison    half_damage_to   to    0.5
237  18     fairy   steel    half_damage_to   to    0.5
238  18     fairy    fire    half_damage_to   to    0.5

[120 rows x 6 columns]

In [28]:
# Primero se separa un listado con los tipos
tipos = df_tabla_efectividad3["type1"].unique()

In [29]:
# Se generara una matriz de 1 de los tipos vs tipos
matriz_tipos = pd.DataFrame(1,index=tipos, columns=tipos)
matriz_tipos

,normal,fighting,flying,poison,ground,rock,bug,ghost,steel,fire,water,grass,electric,psychic,ice,dragon,dark,fairy
normal,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
fighting,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
flying,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
poison,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
ground,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
rock,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
bug,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
ghost,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
steel,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
fire,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
water,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
grass,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
electric,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
psychic,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
ice,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
dragon,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
dark,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
fairy,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [30]:
# Se realiza un bucle con busqueda para asignar los valores de multiplicacion en base
# a la tabla anterior
for fila in df_tabla_efectividad3.itertuples():
  matriz_tipos.loc[fila.type1,fila.type2]=fila.valor
#matriz_tipos

/tmp/ipykernel_1089/3254296579.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matriz_tipos.loc[fila.type1,fila.type2]=fila.valor
/tmp/ipykernel_1089/3254296579.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matriz_tipos.loc[fila.type1,fila.type2]=fila.valor
/tmp/ipykernel_1089/3254296579.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matriz_tipos.loc[fila.type1,fila.type2]=fila.valor
/tmp/ipykernel_1089/3254296579.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matriz_tipos.loc[fila.type1,fila.type2]=fila.valor
/tmp/ipykernel_1089/3254296579.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matriz_tipos.loc[fila.type1,fila.type2]=fila.valor
/tmp/ipykernel_1089/3254296579.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matriz_tipos.loc[fila.type1,fila.type2]=fila.valor
/tmp/ipykernel_1089/3254296579.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matriz_tipos.loc[fila.type1,fila.type2]=fila.valor
/tmp/ipykernel_1089/3254296579.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matriz_tipos.loc[fila.type1,fila.type2]=fila.valor
/tmp/ipykernel_1089/3254296579.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matriz_tipos.loc[fila.type1,fila.type2]=fila.valor
/tmp/ipykernel_1089/3254296579.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matriz_tipos.loc[fila.type1,fila.type2]=fila.valor
/tmp/ipykernel_1089/3254296579.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matriz_tipos.loc[fila.type1,fila.type2]=fila.valor
/tmp/ipykernel_1089/3254296579.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matriz_tipos.loc[fila.type1,fila.type2]=fila.valor
/tmp/ipykernel_1089/3254296579.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matriz_tipos.loc[fila.type1,fila.type2]=fila.valor
/tmp/ipykernel_1089/3254296579.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matriz_tipos.loc[fila.type1,fila.type2]=fila.valor
/tmp/ipykernel_1089/3254296579.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matriz_tipos.loc[fila.type1,fila.type2]=fila.valor
/tmp/ipykernel_1089/3254296579.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matriz_tipos.loc[fila.type1,fila.type2]=fila.valor
/tmp/ipykernel_1089/3254296579.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  matriz_tipos.loc[fila.type1,fila.type2]=fila.valor

In [31]:
matriz_tipos#Matriz final de efectividad tipo atacante vs tipo defensor

,normal,fighting,flying,poison,ground,rock,bug,ghost,steel,fire,water,grass,electric,psychic,ice,dragon,dark,fairy
normal,1,1.0,1.0,1.0,1.0,0.5,1.0,0.0,0.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
fighting,2,1.0,0.5,0.5,1.0,2.0,0.5,0.0,2.0,1.0,1.0,1.0,1.0,0.5,2.0,1.0,2.0,0.5
flying,1,2.0,1.0,1.0,1.0,0.5,2.0,1.0,0.5,1.0,1.0,2.0,0.5,1.0,1.0,1.0,1.0,1.0
poison,1,1.0,1.0,0.5,0.5,0.5,1.0,0.5,0.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0
ground,1,1.0,0.0,2.0,1.0,2.0,0.5,1.0,2.0,2.0,1.0,0.5,2.0,1.0,1.0,1.0,1.0,1.0
rock,1,0.5,2.0,1.0,0.5,1.0,2.0,1.0,0.5,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0
bug,1,0.5,0.5,0.5,1.0,1.0,1.0,0.5,0.5,0.5,1.0,2.0,1.0,2.0,1.0,1.0,2.0,0.5
ghost,0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0
steel,1,1.0,1.0,1.0,1.0,2.0,1.0,1.0,0.5,0.5,0.5,1.0,0.5,1.0,2.0,1.0,1.0,2.0
fire,1,1.0,1.0,1.0,1.0,0.5,2.0,1.0,2.0,0.5,0.5,2.0,1.0,1.0,2.0,0.5,1.0,1.0
water,1,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,0.5,0.5,1.0,1.0,1.0,0.5,1.0,1.0
grass,1,1.0,0.5,0.5,2.0,2.0,0.5,1.0,0.5,0.5,2.0,0.5,1.0,1.0,1.0,0.5,1.0,1.0
electric,1,1.0,2.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,2.0,0.5,0.5,1.0,1.0,0.5,1.0,1.0
psychic,1,2.0,1.0,2.0,1.0,1.0,1.0,1.0,0.5,1.0,1.0,1.0,1.0,0.5,1.0,1.0,0.0,1.0
ice,1,1.0,2.0,1.0,2.0,1.0,1.0,1.0,0.5,0.5,0.5,2.0,1.0,1.0,0.5,2.0,1.0,1.0
dragon,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,0.0
dark,1,0.5,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,0.5,0.5
fairy,1,2.0,1.0,0.5,1.0,1.0,1.0,1.0,0.5,0.5,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0

In [32]:
#Para consultar el tipo podemos crear una funcion
tipo1 = "fire"
tipo2 = "dragon"
matriz_tipos.loc[tipo1,tipo2]

np.float64(0.5)

## Tabla Juegos

## Tabla Naturalezas

In [33]:
#Tabla Naturalezas (id_naturaleza, nombre)No existen generaciones
url_naturalezas = "https://pokeapi.co/api/v2/nature/?limit=1000"
data = requests.get(url_naturalezas)
data = data.json()
lista_url_naturalezas = list(pd.DataFrame(data["results"])["url"])
nature_list = []
for url in lista_url_naturalezas:
  nature_dic={}
  data = requests.get(url)
  data = data.json()
  nature_dic["name"] = data["name"]
  if data["decreased_stat"] == None:
    nature_dic["decreased_stat"] = None
    nature_dic["increased_stat"] = None
  else:
    nature_dic["decreased_stat"] = data["decreased_stat"]["name"]
    nature_dic["increased_stat"] = data["increased_stat"]["name"]
  nature_list.append(nature_dic)
tabla_naturalezas = pd.DataFrame(nature_list)

In [34]:
tabla_naturalezas

       name   decreased_stat   increased_stat
0     hardy             None             None
1      bold           attack          defense
2    modest           attack   special-attack
3      calm           attack  special-defense
4     timid           attack            speed
5    lonely          defense           attack
6    docile             None             None
7      mild          defense   special-attack
8    gentle          defense  special-defense
9     hasty          defense            speed
10  adamant   special-attack           attack
11   impish   special-attack          defense
12  bashful             None             None
13  careful   special-attack  special-defense
14     rash  special-defense   special-attack
15    jolly   special-attack            speed
16  naughty  special-defense           attack
17      lax  special-defense          defense
18   quirky             None             None
19    naive  special-defense            speed
20    brave            speed           attack
21  relaxed            speed          defense
22    quiet            speed   special-attack
23    sassy            speed  special-defense
24  serious             None             None

## Tabla Stats

In [38]:
# Tabla basica de stats(nombre, id)
stats_list = []
url_stats = "https://pokeapi.co/api/v2/stat"
data = requests.get(url_stats)
data = data.json()
for x in data["results"]:
  stats_list.append({"stat":x["name"]})
tabla_stats = pd.DataFrame(stats_list)
tabla_stats

              stat
0               hp
1           attack
2          defense
3   special-attack
4  special-defense
5            speed
6         accuracy
7          evasion
8          special

## Tabla Estados

## Tabla Objetos

## Tabla Habilidades

## Tabla Lugares

## Tabla Temas Musicales

## Tabla Reglas